[package]
name = "terry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = { version = "0.8.0", features = ["nightly"] }
rustc-hash = "1.1.0"