[workspace]
members = [
    "terryc",
    "terryc/ast",
    "terryc/base",
    "terryc/lex",
    "terryc/hir",
    "terryc/mir",
    "terryc/coffer/bytecode",
    "terryc/coffer/bytecode/macro",
    "xtask",
]