[package]
name = "terryc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-hash = "1.1.0"
ariadne = "0.1.5"
clap = { version = "3", features = ["derive"] }
salsa = "0.16.1"