name: CI
on: [push]
jobs:
  ci:
    name: Rust
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --release --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: test
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
